import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Script } from 'node:vm';
const root=fileURLToPath(new URL('../dist/',import.meta.url));
const html=readFileSync(resolve(root,'index.html'),'utf8');
const js=readFileSync(resolve(root,'app.js'),'utf8');
const css=readFileSync(resolve(root,'style.css'),'utf8');
new Script(js,{filename:'app.js'});
for(const [,script] of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)) if(script.trim()) new Script(script);
const files=new Set(['index.html','style.css','app.js']);
for(const [,path] of html.matchAll(/(?:src|href)="([^"#]+)"/g)) if(!/^(?:https?:|data:|mailto:)/.test(path)) files.add(path.split(/[?#]/)[0]);
for(const [,path] of css.matchAll(/url\(['"]?([^)'"\s]+)['"]?\)/g)) if(!/^(?:https?:|data:)/.test(path)) files.add(path);
for(const name of ['hero-natal','cesta-cafe-natal','cesta-doces-natal','cesta-brinde-natal','cesta-afeto-natal','cesta-corporativa-natal','cesta-familia-natal','bonus-foto','bonus-calendario','bonus-textos']) files.add(`assets/${name}.webp`);
const missing=[...files].filter(path=>!existsSync(resolve(root,path)));
if(missing.length) throw new Error('Arquivos ausentes: '+missing.join(', '));
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
if(new Set(ids).size!==ids.length) throw new Error('IDs duplicados no HTML.');
for(const [,anchor] of html.matchAll(/href="#([^"]+)"/g)) if(!ids.includes(anchor)) throw new Error('Âncora ausente: '+anchor);
const checkoutLinks=[...html.matchAll(/href="(https:\/\/pay\.wiapy\.com\/[^"?]+)"/g)].map(m=>m[1]);
if(checkoutLinks.length!==2||!checkoutLinks.includes('https://pay.wiapy.com/wHwV3bFk8')||!checkoutLinks.includes('https://pay.wiapy.com/B43aW3UJt6')) throw new Error('Checkouts diferentes da oferta aprovada.');
if(/Hotmart|somente hoje|termina hoje|R\$ 1\.000 por semana/i.test(html+js)) throw new Error('Referência antiga ou urgência não comprovada encontrada.');
console.log(`Cesta Certa Natal aprovado: JavaScript válido, âncoras e 2 checkouts corretos, ${files.size} arquivos estáticos encontrados.`);
